version: '3.8'
services:
  backend:
    build: ./src
    container_name: mern_backend
    ports:
      - "5000:5000"
    env_file:
      - .env.docker
    networks:
      - mern_net

  frontend:
    build: ./client
    container_name: mern_frontend
    ports:
      - "8632:8632"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    networks:
      - mern_net

networks:
  mern_net:
    driver: bridge
