# backend-deployment + service
apiVersion: apps/v1
kind: Deployment
metadata: { name: backend-deployment }
spec:
  replicas: 3
  selector: { matchLabels: { app: mern-backend } }
  template:
    metadata: { labels: { app: mern-backend } }
    spec:
      containers:
        - name: mern-backend
          image: mern-backend:latest
          imagePullPolicy: Never
          ports: [{ containerPort: 5000 }]
          envFrom: [{ secretRef: { name: backend-env } }]

---
apiVersion: v1
kind: Service
metadata: { name: backend }
spec:
  selector: { app: mern-backend }
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050

