# frontend-deployment + service
apiVersion: apps/v1
kind: Deployment
metadata: { name: frontend-deployment }
spec:
  replicas: 3
  selector: { matchLabels: { app: mern-frontend } }
  template:
    metadata: { labels: { app: mern-frontend } }
    spec:
      containers:
        - name: mern-frontend
          image: mineacuna/mern_stack-frontend:latest  # <- imagen de Docker Hub
          imagePullPolicy: Always 
          ports: [{ containerPort: 8632 }]
          env:
            - name: REACT_APP_API_URL
              value: "http://backend:5000"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: mern-frontend
  type: NodePort
  ports:
    - port: 80          # puerto interno del cluster
      targetPort: 8632  # puerto del contenedor
      nodePort: 30080   # puerto externo (30000–32767)
