apiVersion: v1
kind: Secret
metadata:
  name: backend-env
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://andresacunaurrego:mUUrmYqyFfPmsQaa@cluster0.znhhfhk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
